#!/usr/bin/env python3
"""
Silver Tier Skill for AI Employee
Combines all Silver Tier capabilities in one interface
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime


def get_vault_path() -> Path:
    """Get the vault path"""
    vault = os.getenv('AI_EMPLOYEE_VAULT', './AI_Employee_Vault')
    return Path(vault).resolve()


def check_gmail():
    """Run Gmail watcher to check for new emails"""
    print("\n" + "="*60)
    print("CHECKING GMAIL")
    print("="*60)

    import subprocess
    vault_path = get_vault_path()
    gmail_script = vault_path / 'gmail_watcher.py'

    if not gmail_script.exists():
        print("[FAIL] Gmail watcher not found")
        return False

    result = subprocess.run(
        [sys.executable, str(gmail_script)],
        capture_output=True,
        text=True,
        cwd=str(vault_path.parent)
    )

    print(result.stdout)
    if result.returncode == 0:
        print("\n[OK] Gmail check completed")
        return True
    else:
        print(f"\n[FAIL] Gmail check failed: {result.stderr}")
        return False


def generate_linkedin(category: str = None):
    """Generate LinkedIn post content"""
    print("\n" + "="*60)
    print("GENERATING LINKEDIN POST")
    print("="*60)

    import subprocess
    vault_path = get_vault_path()
    linkedin_script = vault_path / 'linkedin_watcher.py'

    cmd = [sys.executable, str(linkedin_script), 'generate']
    if category:
        cmd.extend(['--category', category])

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        cwd=str(vault_path.parent)
    )

    print(result.stdout)
    return result.returncode == 0


def queue_linkedin(category: str = None):
    """Queue a LinkedIn post for approval"""
    print("\n" + "="*60)
    print("QUEUING LINKEDIN POST")
    print("="*60)

    import subprocess
    vault_path = get_vault_path()
    linkedin_script = vault_path / 'linkedin_watcher.py'

    cmd = [sys.executable, str(linkedin_script), 'queue']
    if category:
        cmd.extend(['--category', category])

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        cwd=str(vault_path.parent)
    )

    print(result.stdout)
    return result.returncode == 0


def create_plan(task_id: str = None):
    """Create a plan for a task"""
    print("\n" + "="*60)
    print("CREATING PLAN")
    print("="*60)

    vault_path = get_vault_path()
    needs_action = vault_path / 'Needs_Action'

    if task_id:
        # Find specific task
        task_files = list(needs_action.glob(f"*{task_id}*.md"))
    else:
        # Get most recent task
        task_files = sorted(needs_action.glob("*.md"), key=lambda p: p.stat().st_mtime, reverse=True)

    if not task_files:
        print("[FAIL] No tasks found in Needs_Action")
        return False

    task_file = task_files[0]
    print(f"Creating plan for: {task_file.name}")

    # Read task content
    content = task_file.read_text(encoding='utf-8')

    # Create plan
    plan_folder = vault_path / 'Plans'
    plan_folder.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    plan_file = plan_folder / f"PLAN_{task_file.stem}_{timestamp}.md"

    plan_content = f"""---
type: plan
source_task: {task_file.name}
created: {datetime.now().isoformat()}
status: pending
---

# Plan for Task: {task_file.stem}

## Task Description
```
{content[:500]}...
```

## Proposed Steps
1. [ ] Analyze the task requirements
2. [ ] Gather necessary information
3. [ ] Execute the primary action
4. [ ] Verify results
5. [ ] Complete and move to Done

## Resources Needed
- [ ] Review task content
- [ ] Check relevant documentation
- [ ] Execute action

## Estimated Time
- Analysis: 5 minutes
- Execution: 15 minutes
- Verification: 5 minutes
- Total: 25 minutes

## Notes
_Add any specific notes about this plan_

---

*Plan generated by AI Employee - Silver Tier*
"""

    plan_file.write_text(plan_content, encoding='utf-8')
    print(f"[OK] Plan created: {plan_file.name}")

    return True


def create_approval(approval_type: str, details: dict):
    """Create an approval request"""
    print("\n" + "="*60)
    print("CREATING APPROVAL REQUEST")
    print("="*60)

    import subprocess

    cmd = [
        sys.executable,
        '.claude/skills/approval-workflow.py',
        'create-request',
        '--action-type', approval_type,
        '--details', json.dumps(details)
    ]

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        cwd=str(get_vault_path().parent)
    )

    print(result.stdout)
    return result.returncode == 0


def check_approved():
    """Check and execute approved items"""
    print("\n" + "="*60)
    print("CHECKING APPROVED ITEMS")
    print("="*60)

    import subprocess

    cmd = [
        sys.executable,
        '.claude/skills/approval-workflow.py',
        'check-approved',
        '--execute'
    ]

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        cwd=str(get_vault_path().parent)
    )

    print(result.stdout)
    return result.returncode == 0


def run_scheduled():
    """Run scheduled tasks"""
    print("\n" + "="*60)
    print("RUNNING SCHEDULED TASKS")
    print("="*60)

    import subprocess
    vault_path = get_vault_path()
    scheduler_script = vault_path / 'scheduler.py'

    result = subprocess.run(
        [sys.executable, str(scheduler_script), 'list'],
        capture_output=True,
        text=True,
        cwd=str(vault_path.parent)
    )

    print(result.stdout)
    return result.returncode == 0


def main():
    """Main entry point"""
    parser = argparse.ArgumentParser(description='Silver Tier Skill for AI Employee')
    parser.add_argument('action', choices=[
        'check-gmail', 'generate-linkedin', 'queue-linkedin',
        'create-plan', 'create-approval', 'check-approved', 'run-scheduled'
    ], help='Action to perform')
    parser.add_argument('--task-id', help='Task ID for plan creation')
    parser.add_argument('--category', help='LinkedIn category')
    parser.add_argument('--approval-type', help='Approval request type')
    parser.add_argument('--details', help='Approval details (JSON)')

    args = parser.parse_args()

    if args.action == 'check-gmail':
        check_gmail()

    elif args.action == 'generate-linkedin':
        generate_linkedin(args.category)

    elif args.action == 'queue-linkedin':
        queue_linkedin(args.category)

    elif args.action == 'create-plan':
        create_plan(args.task_id)

    elif args.action == 'create-approval':
        if not args.approval_type:
            print("Error: --approval-type required")
            sys.exit(1)
        details = json.loads(args.details) if args.details else {}
        create_approval(args.approval_type, details)

    elif args.action == 'check-approved':
        check_approved()

    elif args.action == 'run-scheduled':
        run_scheduled()


if __name__ == '__main__':
    main()
